# Generated by Django 4.1.5 on 2023-02-08 08:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.SmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('number', models.SmallIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_time', models.DateTimeField()),
                ('to_time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_route.bus')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus_route.route')),
            ],
            options={
                'unique_together': {('bus', 'route', 'from_time', 'to_time')},
            },
        ),
        migrations.AddField(
            model_name='bus',
            name='routes',
            field=models.ManyToManyField(through='bus_route.BusRoute', to='bus_route.route'),
        ),
    ]
