# Generated by Django 3.2.16 on 2023-02-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus_route', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bus',
            options={'verbose_name': 'bus', 'verbose_name_plural': 'buses'},
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='name',
            new_name='bus_name',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='number',
            new_name='bus_number',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='name',
            new_name='route_name',
        ),
        migrations.RenameField(
            model_name='route',
            old_name='number',
            new_name='route_number',
        ),
    ]
